name: fts

on: push

jobs:
  build:

    runs-on: windows-latest
    steps:
    - name: Install Autoit
      run: |
           Invoke-WebRequest -Uri https://www.autoitscript.com/cgi-bin/getfile.pl?autoit3/autoit-v3-setup.exe -OutFile autoit-v3-setup.exe
           ./autoit-v3-setup.exe /S

    - name: Checkout repo
      run: |
           cd C:\"Program Files (x86)"\AutoIt3\Aut2Exe
           git clone https://github.com/rcmaehl/FreezeToStock --depth 1
      
    - name: Compile
      run: |
           cd C:\"Program Files (x86)"\AutoIt3
           Move-Item Include Aut2Exe\FreezeToStock
           cd Aut2Exe
           Move-Item aut2exe.exe FreezeToStock
           cd NotCPUCores
           ./Aut2exe.exe /in FTS.au3 /out FTS.exe /comp 4 /nopack /icon icon.ico


    - name: Upload
      uses: actions/upload-artifact@v2
      with:
       name: FTS
       path: C:\Program Files (x86)\AutoIt3\Aut2Exe\FreezeToStock\FTS.exe
       if-no-files-found: error
